"""Initial schema with pgvector

Revision ID: 1638a3952bd5
Revises: 
Create Date: 2025-12-13 19:30:49.283746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1638a3952bd5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_zh', sa.String(length=50), nullable=False),
    sa.Column('abbrev_zh', sa.String(length=10), nullable=False),
    sa.Column('testament', sa.String(length=2), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("testament IN ('OT', 'NT')", name='check_testament'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_zh'),
    sa.UniqueConstraint('order_index')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('PERSON', 'PLACE', 'GROUP', 'EVENT')", name='check_entity_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'type', name='uq_entity_name_type')
    )
    op.create_index('idx_entities_type', 'entities', ['type'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('DOCTRINE', 'MORAL', 'HISTORICAL', 'PROPHETIC', 'OTHER')", name='check_topic_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'number', name='uq_chapter_book_number')
    )
    op.create_table('pericopes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chapter_start', sa.Integer(), nullable=False),
    sa.Column('verse_start', sa.Integer(), nullable=False),
    sa.Column('chapter_end', sa.Integer(), nullable=False),
    sa.Column('verse_end', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Create HNSW index for embedding vector search
    op.execute('''
        CREATE INDEX idx_pericopes_embedding ON pericopes
        USING hnsw (embedding vector_cosine_ops)
    ''')
    op.create_table('verses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('verse', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('pericope_id', sa.Integer(), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', text)", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pericope_id'], ['pericopes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'chapter', 'verse', name='uq_verse_reference')
    )
    op.create_index('idx_verses_book_chapter', 'verses', ['book_id', 'chapter'], unique=False)
    op.create_index('idx_verses_tsv', 'verses', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('verse_entities',
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('verse_id', 'entity_id')
    )
    op.create_index('idx_verse_entities_entity', 'verse_entities', ['entity_id'], unique=False)
    op.create_table('verse_topics',
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weight >= 0 AND weight <= 1', name='check_weight_range'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('verse_id', 'topic_id')
    )
    op.create_index('idx_verse_topics_weight', 'verse_topics', ['weight'], unique=False, postgresql_ops={'weight': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_verse_topics_weight', table_name='verse_topics', postgresql_ops={'weight': 'DESC'})
    op.drop_table('verse_topics')
    op.drop_index('idx_verse_entities_entity', table_name='verse_entities')
    op.drop_table('verse_entities')
    op.drop_index('idx_verses_tsv', table_name='verses', postgresql_using='gin')
    op.drop_index('idx_verses_book_chapter', table_name='verses')
    op.drop_table('verses')
    op.execute('DROP INDEX IF EXISTS idx_pericopes_embedding')
    op.drop_table('pericopes')
    op.drop_table('chapters')
    op.drop_table('topics')
    op.drop_index('idx_entities_type', table_name='entities')
    op.drop_table('entities')
    op.drop_table('books')
    # ### end Alembic commands ###
